### PR TITLE
Fix errors caused by latest version of FFMPEG

### PR DESCRIPTION
**Pull request by ethanmay**
Also added error handling to callback function.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
What is `vframes` for?

**Comment by ethanmay** [comment]
From [the documentation](https://ffmpeg.org/ffmpeg.html#Video-Options): `-vframes` number (output): Set the number of video frames to output.

You were using it properly, but placing it before the input parameters was causing the code to break. Moving it further along in the command fixed the problem.

**Comment by vadimdemedes** [comment]
Cool, thanks!

**Comment by vadimdemedes** [comment]
Published on npm 🎉

**Pull request merged**
